version: '3'

services:
  craftbeer:
    build: ./
    container_name: app-craftbeer
    volumes:
      - ./:/usr/src/app
    ports:
      - 9000:9000
    networks:
      - craftbeer-network
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres-craftbeer
    tty: true
    expose:
    - 5432
    networks:
      - craftbeer-network
    environment:
      POSTGRES_USER: craftbeer
      POSTGRES_PASSWORD: 95589558
      POSTGRES_DB: craftbeer

networks:
  craftbeer-network:
    driver: bridge
